version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=coffee_user
      - DATABASE_PASSWORD=coffee_password
      - DATABASE_DBNAME=coffee_cups
    depends_on:
      - postgres
    volumes:
      - ./configs:/root/configs

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=coffee_user
      - POSTGRES_PASSWORD=coffee_password
      - POSTGRES_DB=coffee_cups
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
